using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace ProMvvm.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class ProMvvmGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "ProMvvm.GeneratePropertyPathsAttribute";

    private static readonly DiagnosticDescriptor GenericTypeNotSupported = new(
        "PMVVM001",
        "Generic property-path targets are not supported",
        "Property-path generation for '{0}' is not supported because it or a containing type is generic",
        "ProMvvm.SourceGeneration",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
            SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var isRuntimeAssembly = context.CompilationProvider.Select(
            static (compilation, _) => string.Equals(
                compilation.AssemblyName,
                "ProMvvm",
                StringComparison.Ordinal));

        context.RegisterSourceOutput(
            isRuntimeAssembly,
            static (productionContext, generate) =>
            {
                if (generate)
                {
                    productionContext.AddSource(
                        "WhenAnyValueExtensions.Arity3To12.g.cs",
                        MultiArityEmitter.Emit());
                }
            });

        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax,
                static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol)
            .Collect();

        context.RegisterSourceOutput(
            targets,
            static (productionContext, symbols) => EmitPropertyPaths(productionContext, symbols));
    }

    private static void EmitPropertyPaths(
        SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol> symbols)
    {
        var visited = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var symbol in symbols)
        {
            if (!visited.Add(symbol))
            {
                continue;
            }

            if (IsGeneric(symbol))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    GenericTypeNotSupported,
                    symbol.Locations.FirstOrDefault(),
                    symbol.ToDisplayString()));
                continue;
            }

            var source = EmitPropertyPathClass(symbol);
            context.AddSource(GetHintName(symbol), source);
        }
    }

    private static bool IsGeneric(INamedTypeSymbol symbol)
    {
        for (INamedTypeSymbol? current = symbol; current is not null; current = current.ContainingType)
        {
            if (current.IsGenericType)
            {
                return true;
            }
        }

        return false;
    }

    private static string EmitPropertyPathClass(INamedTypeSymbol symbol)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");

        if (!symbol.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ")
                .Append(symbol.ContainingNamespace.ToDisplayString())
                .AppendLine(";")
                .AppendLine();
        }

        var accessibility = IsPublic(symbol) ? "public" : "internal";
        var className = GetGeneratedClassName(symbol);
        var sourceType = symbol.ToDisplayString(TypeDisplayFormat);

        builder.AppendLine("/// <summary>Generated reflection-free property descriptors.</summary>")
            .Append(accessibility)
            .Append(" static class ")
            .Append(className)
            .AppendLine()
            .AppendLine("{");

        foreach (var property in GetGeneratedProperties(symbol))
        {
            var propertyType = property.Type.ToDisplayString(TypeDisplayFormat);
            var propertyName = EscapeIdentifier(property.Name);
            builder.Append("    /// <summary>Describes <see cref=\"")
                .Append(sourceType)
                .Append('.')
                .Append(propertyName)
                .AppendLine("\"/>.</summary>");
            builder.Append("    public static readonly global::ProMvvm.PropertyPath<")
                .Append(sourceType)
                .Append(", ")
                .Append(propertyType)
                .Append("> ")
                .Append(propertyName)
                .AppendLine(" =")
                .Append("        global::ProMvvm.PropertyPath.Create<")
                .Append(sourceType)
                .Append(", ")
                .Append(propertyType)
                .AppendLine(">(")
                .Append("            \"")
                .Append(EscapeString(property.Name))
                .AppendLine("\",")
                .Append("            static source => source.")
                .Append(propertyName)
                .AppendLine(");")
                .AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static IEnumerable<GeneratedProperty> GetGeneratedProperties(INamedTypeSymbol symbol)
    {
        var properties = new Dictionary<string, GeneratedProperty>(StringComparer.Ordinal);
        foreach (var property in symbol.GetMembers().OfType<IPropertySymbol>().Where(IsSupportedProperty))
        {
            properties[property.Name] = new GeneratedProperty(property.Name, property.Type);
        }

        foreach (var field in symbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (!field.IsStatic && HasGeneratedPropertyAttribute(field))
            {
                var propertyName = GetGeneratedPropertyName(field.Name);
                if (propertyName.Length > 0)
                {
                    properties[propertyName] = new GeneratedProperty(propertyName, field.Type);
                }
            }
        }

        return properties.Values.OrderBy(static property => property.Name, StringComparer.Ordinal);
    }

    private static bool HasGeneratedPropertyAttribute(IFieldSymbol field) =>
        field.GetAttributes().Any(static attribute =>
        {
            var name = attribute.AttributeClass?.ToDisplayString();
            return string.Equals(
                       name,
                       "CommunityToolkit.Mvvm.ComponentModel.ObservablePropertyAttribute",
                       StringComparison.Ordinal) ||
                   string.Equals(
                       name,
                       "ReactiveUI.SourceGenerators.ReactiveAttribute",
                       StringComparison.Ordinal);
        });

    private static string GetGeneratedPropertyName(string fieldName)
    {
        var name = fieldName.StartsWith("m_", StringComparison.Ordinal)
            ? fieldName.Substring(2)
            : fieldName.TrimStart('_');
        return name.Length == 0
            ? string.Empty
            : char.ToUpperInvariant(name[0]) + name.Substring(1);
    }

    private static bool IsSupportedProperty(IPropertySymbol property) =>
        !property.IsStatic &&
        !property.IsIndexer &&
        property.CanBeReferencedByName &&
        property.GetMethod is
        {
            DeclaredAccessibility: Accessibility.Public or
            Accessibility.Internal or Accessibility.ProtectedOrInternal
        };

    private static bool IsPublic(INamedTypeSymbol symbol)
    {
        for (INamedTypeSymbol? current = symbol; current is not null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility != Accessibility.Public)
            {
                return false;
            }
        }

        return true;
    }

    private static string GetGeneratedClassName(INamedTypeSymbol symbol)
    {
        var names = new Stack<string>();
        for (INamedTypeSymbol? current = symbol; current is not null; current = current.ContainingType)
        {
            names.Push(current.Name);
        }

        return string.Join("_", names) + "PropertyPaths";
    }

    private static string GetHintName(INamedTypeSymbol symbol)
    {
        var fullName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var builder = new StringBuilder(fullName.Length + 20);
        foreach (var character in fullName)
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.Append(".PropertyPaths.g.cs").ToString();
    }

    private static string EscapeIdentifier(string identifier) =>
        SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None ? "@" + identifier : identifier;

    private static string EscapeString(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class GeneratedProperty(string name, ITypeSymbol type)
    {
        public string Name { get; } = name;

        public ITypeSymbol Type { get; } = type;
    }
}

internal static class MultiArityEmitter
{
    public static string Emit()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine("using System.Diagnostics.CodeAnalysis;")
            .AppendLine("using System.Linq.Expressions;")
            .AppendLine()
            .AppendLine("namespace ProMvvm;")
            .AppendLine()
            .AppendLine("[ExcludeFromCodeCoverage]")
            .AppendLine("public static partial class WhenAnyValueMultiExtensions")
            .AppendLine("{");

        for (var arity = 3; arity <= 12; arity++)
        {
            EmitTypedSelector(builder, arity, withAdapter: false);
            EmitTypedSelector(builder, arity, withAdapter: true);
            EmitExpressionSelector(builder, arity, withAdapter: false);
            EmitExpressionSelector(builder, arity, withAdapter: true);
            EmitStringSelector(builder, arity);
            EmitTypedTuple(builder, arity, withAdapter: false);
            EmitTypedTuple(builder, arity, withAdapter: true);
            EmitExpressionTuple(builder, arity, withAdapter: false);
            EmitExpressionTuple(builder, arity, withAdapter: true);
            EmitStringTuple(builder, arity);
        }

        builder.AppendLine("}");

        for (var arity = 3; arity <= 12; arity++)
        {
            EmitObservable(builder, arity);
        }

        return builder.ToString();
    }

    private static void EmitTypedSelector(StringBuilder builder, int arity, bool withAdapter)
    {
        builder.Append("    /// <summary>Observes ")
            .Append(arity)
            .AppendLine(" AOT-safe paths and projects their latest values.</summary>")
            .Append("    public static IObservable<TResult> WhenAnyValue<TSource, ")
            .Append(TypeParameters(arity))
            .AppendLine(", TResult>(")
            .AppendLine("        this TSource source,");
        EmitParameters(builder, arity, "PropertyPath<TSource, T{0}> property{0}");
        builder.Append("        Func<")
            .Append(TypeParameters(arity))
            .AppendLine(", TResult> selector,");
        if (withAdapter)
        {
            builder.AppendLine("        IPropertyNotificationAdapter notificationAdapter,");
        }

        builder.AppendLine("        bool isDistinct = true,")
            .AppendLine("        IEqualityComparer<TResult>? comparer = null)")
            .AppendLine("        where TSource : class")
            .AppendLine("    {")
            .AppendLine("        ArgumentNullException.ThrowIfNull(source);");
        for (var index = 1; index <= arity; index++)
        {
            builder.Append("        ArgumentNullException.ThrowIfNull(property")
                .Append(index)
                .AppendLine(");");
        }

        builder.AppendLine("        ArgumentNullException.ThrowIfNull(selector);");
        if (withAdapter)
        {
            builder.AppendLine("        ArgumentNullException.ThrowIfNull(notificationAdapter);");
        }

        builder
            .Append("        return new CombineLatestObservable<")
            .Append(TypeParameters(arity))
            .AppendLine(", TResult>(");
        for (var index = 1; index <= arity; index++)
        {
            builder.Append("            source.WhenAnyValue(property")
                .Append(index);
            if (withAdapter)
            {
                builder.Append(", notificationAdapter");
            }

            builder
                .AppendLine(", isDistinct),");
        }

        builder.AppendLine("            selector,")
            .AppendLine("            isDistinct,")
            .AppendLine("            comparer ?? EqualityComparer<TResult>.Default);")
            .AppendLine("    }")
            .AppendLine();
    }

    private static void EmitExpressionSelector(StringBuilder builder, int arity, bool withAdapter)
    {
        builder.Append("    /// <summary>Observes ")
            .Append(arity)
            .AppendLine(" expression paths and projects their latest values.</summary>")
            .AppendLine("    [RequiresUnreferencedCode(\"Expression compatibility uses reflected metadata. Use typed PropertyPath arguments for trimming and NativeAOT.\")]")
            .Append("    public static IObservable<TResult> WhenAnyValue<TSource, TResult, ")
            .Append(TypeParameters(arity))
            .AppendLine(">(")
            .AppendLine("        this TSource source,");
        EmitParameters(builder, arity, "Expression<Func<TSource, T{0}>> property{0}");
        builder.Append("        Func<")
            .Append(TypeParameters(arity))
            .AppendLine(", TResult> selector,");
        if (withAdapter)
        {
            builder.AppendLine("        IPropertyNotificationAdapter notificationAdapter,");
        }

        builder.AppendLine("        bool isDistinct = true,")
            .AppendLine("        IEqualityComparer<TResult>? comparer = null)")
            .AppendLine("        where TSource : class =>")
            .AppendLine("        source.WhenAnyValue(");
        for (var index = 1; index <= arity; index++)
        {
            builder.Append("            ExpressionPropertyPath.Create(property")
                .Append(index)
                .AppendLine("),");
        }

        builder.AppendLine("            selector,");
        if (withAdapter)
        {
            builder.AppendLine("            notificationAdapter,");
        }

        builder.AppendLine("            isDistinct,")
            .AppendLine("            comparer);")
            .AppendLine();
    }

    private static void EmitStringSelector(StringBuilder builder, int arity)
    {
        builder.Append("    /// <summary>ReactiveUI-compatible projection of ")
            .Append(arity)
            .AppendLine(" public properties observed by name.</summary>")
            .AppendLine("    [RequiresUnreferencedCode(\"String property compatibility resolves public property metadata by name. Use generated or typed PropertyPath arguments for trimming and NativeAOT.\")]")
            .Append("    public static IObservable<TResult> WhenAnyValue<TSource, TResult, ")
            .Append(TypeParameters(arity))
            .AppendLine(">(")
            .AppendLine("        this TSource source,");
        EmitParameters(builder, arity, "string property{0}Name");
        builder.Append("        Func<")
            .Append(TypeParameters(arity))
            .AppendLine(", TResult> selector,")
            .AppendLine("        bool isDistinct = true)")
            .AppendLine("        where TSource : class")
            .AppendLine("    {")
            .AppendLine("        ArgumentNullException.ThrowIfNull(source);")
            .AppendLine("        ArgumentNullException.ThrowIfNull(selector);")
            .AppendLine("        return source.WhenAnyValue(");
        EmitArguments(builder, arity, "StringPropertyPath.Create<TSource, T{0}>(source, property{0}Name)");
        builder.AppendLine("            selector,")
            .AppendLine("            isDistinct);")
            .AppendLine("    }")
            .AppendLine();
    }

    private static void EmitTypedTuple(StringBuilder builder, int arity, bool withAdapter)
    {
        builder.Append("    /// <summary>Observes ")
            .Append(arity)
            .AppendLine(" AOT-safe paths and emits value tuples.</summary>")
            .Append("    public static IObservable<")
            .Append(TupleType(arity))
            .Append("> WhenAnyValue<TSource, ")
            .Append(TypeParameters(arity))
            .AppendLine(">(")
            .AppendLine("        this TSource source,");
        EmitParameters(builder, arity, "PropertyPath<TSource, T{0}> property{0}");
        if (withAdapter)
        {
            builder.AppendLine("        IPropertyNotificationAdapter notificationAdapter,");
        }

        builder.AppendLine("        bool isDistinct = true) where TSource : class =>")
            .AppendLine("        source.WhenAnyValue(");
        EmitArguments(builder, arity, "property{0}");
        builder.Append("            static (")
            .Append(ValueParameters(arity))
            .Append(") => (")
            .Append(ValueArguments(arity))
            .AppendLine("),");
        if (withAdapter)
        {
            builder.AppendLine("            notificationAdapter,");
        }

        builder.AppendLine("            isDistinct);")
            .AppendLine();
    }

    private static void EmitExpressionTuple(StringBuilder builder, int arity, bool withAdapter)
    {
        builder.Append("    /// <summary>Observes ")
            .Append(arity)
            .AppendLine(" expression paths and emits value tuples.</summary>")
            .AppendLine("    [RequiresUnreferencedCode(\"Expression compatibility uses reflected metadata. Use typed PropertyPath arguments for trimming and NativeAOT.\")]")
            .Append("    public static IObservable<")
            .Append(TupleType(arity))
            .Append("> WhenAnyValue<TSource, ")
            .Append(TypeParameters(arity))
            .AppendLine(">(")
            .AppendLine("        this TSource source,");
        EmitParameters(builder, arity, "Expression<Func<TSource, T{0}>> property{0}");
        if (withAdapter)
        {
            builder.AppendLine("        IPropertyNotificationAdapter notificationAdapter,");
        }

        builder.AppendLine("        bool isDistinct = true) where TSource : class =>")
            .AppendLine("        source.WhenAnyValue(");
        EmitArguments(builder, arity, "ExpressionPropertyPath.Create(property{0})");
        builder.Append("            static (")
            .Append(ValueParameters(arity))
            .Append(") => (")
            .Append(ValueArguments(arity))
            .AppendLine("),");
        if (withAdapter)
        {
            builder.AppendLine("            notificationAdapter,");
        }

        builder.AppendLine("            isDistinct);")
            .AppendLine();
    }

    private static void EmitStringTuple(StringBuilder builder, int arity)
    {
        builder.Append("    /// <summary>ReactiveUI-compatible observation of ")
            .Append(arity)
            .AppendLine(" public properties by name as a value tuple.</summary>")
            .AppendLine("    [RequiresUnreferencedCode(\"String property compatibility resolves public property metadata by name. Use generated or typed PropertyPath arguments for trimming and NativeAOT.\")]")
            .Append("    public static IObservable<")
            .Append(TupleType(arity))
            .Append("> WhenAnyValue<TSource, ")
            .Append(TypeParameters(arity))
            .AppendLine(">(")
            .AppendLine("        this TSource source,");
        EmitParameters(builder, arity, "string property{0}Name");
        builder.AppendLine("        bool isDistinct = true) where TSource : class =>")
            .AppendLine("        source.WhenAnyValue(");
        EmitArguments(builder, arity, "StringPropertyPath.Create<TSource, T{0}>(source, property{0}Name)");
        builder.Append("            static (")
            .Append(ValueParameters(arity))
            .Append(") => (")
            .Append(ValueArguments(arity))
            .AppendLine("),")
            .AppendLine("            isDistinct);")
            .AppendLine();
    }

    private static void EmitObservable(StringBuilder builder, int arity)
    {
        builder.AppendLine("[ExcludeFromCodeCoverage]")
            .Append("internal sealed class CombineLatestObservable<")
            .Append(TypeParameters(arity))
            .AppendLine(", TResult>(");
        EmitParameters(builder, arity, "IObservable<T{0}> source{0}");
        builder.Append("    Func<")
            .Append(TypeParameters(arity))
            .AppendLine(", TResult> selector,")
            .AppendLine("    bool isDistinct,")
            .AppendLine("    IEqualityComparer<TResult> comparer) : IObservable<TResult>")
            .AppendLine("{")
            .AppendLine("    public IDisposable Subscribe(IObserver<TResult> observer)")
            .AppendLine("    {")
            .AppendLine("        ArgumentNullException.ThrowIfNull(observer);")
            .AppendLine("        var subscription = new Subscription(observer, selector, isDistinct, comparer);")
            .Append("        subscription.Connect(")
            .Append(Arguments(arity, "source{0}"))
            .AppendLine(");")
            .AppendLine("        return subscription;")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    private sealed class Subscription(")
            .AppendLine("        IObserver<TResult> observer,")
            .Append("        Func<")
            .Append(TypeParameters(arity))
            .AppendLine(", TResult> selector,")
            .AppendLine("        bool isDistinct,")
            .AppendLine("        IEqualityComparer<TResult> comparer) : IDisposable")
            .AppendLine("    {")
            .AppendLine("        private readonly object _gate = new();");

        for (var index = 1; index <= arity; index++)
        {
            builder.Append("        private IDisposable? _subscription")
                .Append(index)
                .AppendLine(";");
            builder.Append("        private T")
                .Append(index)
                .Append("? _value")
                .Append(index)
                .AppendLine(";");
            builder.Append("        private bool _hasValue")
                .Append(index)
                .AppendLine(";");
        }

        builder.AppendLine("        private TResult? _lastResult;")
            .AppendLine("        private bool _hasLastResult;")
            .AppendLine("        private bool _stopped;")
            .AppendLine()
            .AppendLine("        public void Connect(");
        EmitParameters(builder, arity, "            IObservable<T{0}> input{0}", trailingComma: false);
        builder.AppendLine("        )")
            .AppendLine("        {")
            .AppendLine("            try")
            .AppendLine("            {");
        for (var index = 1; index <= arity; index++)
        {
            builder.Append("                if (!ConnectSource")
                .Append(index)
                .Append("(input")
                .Append(index)
                .AppendLine("))")
                .AppendLine("                {")
                .AppendLine("                    return;")
                .AppendLine("                }");
        }

        builder.AppendLine("            }")
            .AppendLine("            catch")
            .AppendLine("            {")
            .AppendLine("                Dispose();")
            .AppendLine("                throw;")
            .AppendLine("            }")
            .AppendLine("        }")
            .AppendLine();

        for (var index = 1; index <= arity; index++)
        {
            builder.Append("        private bool ConnectSource")
                .Append(index)
                .Append("(IObservable<T")
                .Append(index)
                .Append("> input)")
                .AppendLine()
                .AppendLine("        {")
                .Append("            var current = input.Subscribe(new SourceObserver")
                .Append(index)
                .AppendLine("(this));")
                .AppendLine("            lock (_gate)")
                .AppendLine("            {")
                .AppendLine("                if (_stopped)")
                .AppendLine("                {")
                .AppendLine("                    current.Dispose();")
                .AppendLine("                    return false;")
                .AppendLine("                }")
                .Append("                _subscription")
                .Append(index)
                .AppendLine(" = current;")
                .AppendLine("                return true;")
                .AppendLine("            }")
                .AppendLine("        }")
                .AppendLine();
        }

        builder.AppendLine("        public void Dispose()")
            .AppendLine("        {")
            .AppendLine("            lock (_gate)")
            .AppendLine("            {")
            .AppendLine("                Stop();")
            .AppendLine("            }")
            .AppendLine("        }")
            .AppendLine();

        for (var index = 1; index <= arity; index++)
        {
            builder.Append("        private void Next")
                .Append(index)
                .Append("(T")
                .Append(index)
                .Append(" value)")
                .AppendLine()
                .AppendLine("        {")
                .AppendLine("            lock (_gate)")
                .AppendLine("            {")
                .AppendLine("                if (_stopped)")
                .AppendLine("                {")
                .AppendLine("                    return;")
                .AppendLine("                }")
                .Append("                _value")
                .Append(index)
                .AppendLine(" = value;")
                .Append("                _hasValue")
                .Append(index)
                .AppendLine(" = true;")
                .AppendLine("                Publish();")
                .AppendLine("            }")
                .AppendLine("        }")
                .AppendLine();
        }

        builder.AppendLine("        private void Publish()")
            .AppendLine("        {")
            .Append("            if (")
            .Append(HasValuesExpression(arity))
            .AppendLine(")")
            .AppendLine("            {")
            .AppendLine("                return;")
            .AppendLine("            }")
            .AppendLine()
            .AppendLine("            TResult result;")
            .AppendLine("            try")
            .AppendLine("            {")
            .Append("                result = selector(")
            .Append(Arguments(arity, "_value{0}!"))
            .AppendLine(");")
            .AppendLine("            }")
            .AppendLine("            catch (Exception error)")
            .AppendLine("            {")
            .AppendLine("                Error(error);")
            .AppendLine("                return;")
            .AppendLine("            }")
            .AppendLine()
            .AppendLine("            if (isDistinct && _hasLastResult && comparer.Equals(_lastResult!, result))")
            .AppendLine("            {")
            .AppendLine("                return;")
            .AppendLine("            }")
            .AppendLine()
            .AppendLine("            _lastResult = result;")
            .AppendLine("            _hasLastResult = true;")
            .AppendLine("            try")
            .AppendLine("            {")
            .AppendLine("                observer.OnNext(result);")
            .AppendLine("            }")
            .AppendLine("            catch")
            .AppendLine("            {")
            .AppendLine("                Stop();")
            .AppendLine("                throw;")
            .AppendLine("            }")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine("        private void Error(Exception error)")
            .AppendLine("        {")
            .AppendLine("            lock (_gate)")
            .AppendLine("            {")
            .AppendLine("                if (_stopped)")
            .AppendLine("                {")
            .AppendLine("                    return;")
            .AppendLine("                }")
            .AppendLine("                Stop();")
            .AppendLine("                observer.OnError(error);")
            .AppendLine("            }")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine("        private void Stop()")
            .AppendLine("        {")
            .AppendLine("            if (_stopped)")
            .AppendLine("            {")
            .AppendLine("                return;")
            .AppendLine("            }")
            .AppendLine("            _stopped = true;");

        for (var index = 1; index <= arity; index++)
        {
            builder.Append("            _subscription")
                .Append(index)
                .AppendLine("?.Dispose();")
                .Append("            _subscription")
                .Append(index)
                .AppendLine(" = null;");
        }

        builder.AppendLine("        }")
            .AppendLine();

        for (var index = 1; index <= arity; index++)
        {
            builder.Append("        private sealed class SourceObserver")
                .Append(index)
                .Append("(Subscription owner) : IObserver<T")
                .Append(index)
                .AppendLine(">")
                .AppendLine("        {")
                .AppendLine("            public void OnCompleted()")
                .AppendLine("            {")
                .AppendLine("            }")
                .AppendLine()
                .AppendLine("            public void OnError(Exception error) => owner.Error(error);")
                .AppendLine()
                .Append("            public void OnNext(T")
                .Append(index)
                .Append(" value) => owner.Next")
                .Append(index)
                .AppendLine("(value);")
                .AppendLine("        }")
                .AppendLine();
        }

        builder.AppendLine("    }")
            .AppendLine("}")
            .AppendLine();
    }

    private static void EmitParameters(
        StringBuilder builder,
        int arity,
        string format,
        bool trailingComma = true)
    {
        for (var index = 1; index <= arity; index++)
        {
            builder.Append("        ")
                .Append(string.Format(CultureInfo.InvariantCulture, format, index));
            if (index < arity || trailingComma)
            {
                builder.Append(',');
            }

            builder.AppendLine();
        }
    }

    private static void EmitArguments(StringBuilder builder, int arity, string format)
    {
        for (var index = 1; index <= arity; index++)
        {
            builder.Append("            ")
                .Append(string.Format(CultureInfo.InvariantCulture, format, index))
                .AppendLine(",");
        }
    }

    private static string TypeParameters(int arity) =>
        string.Join(", ", Enumerable.Range(1, arity).Select(static index => "T" + index));

    private static string Arguments(int arity, string format) =>
        string.Join(", ", Enumerable.Range(1, arity).Select(index =>
            string.Format(CultureInfo.InvariantCulture, format, index)));

    private static string ValueParameters(int arity) =>
        string.Join(", ", Enumerable.Range(1, arity).Select(static index => "value" + index));

    private static string ValueArguments(int arity) =>
        string.Join(", ", Enumerable.Range(1, arity).Select(static index => "value" + index));

    private static string TupleType(int arity) =>
        "(" + string.Join(", ", Enumerable.Range(1, arity).Select(static index =>
            "T" + index + " Value" + index)) + ")";

    private static string HasValuesExpression(int arity) =>
        string.Join(" || ", Enumerable.Range(1, arity).Select(static index => "!_hasValue" + index));
}
